version: '3.8'
services:
  learn-nestjs-dev:
    image: 'postgres:13'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: infinitedim
      POSTGRES_PASSWORD: 40027020
      POSTGRES_DB: bookmarkapp
    networks:
      - infinitedim
  learn-nestjs-test:
    image: 'postgres:13'
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: infinitedim
      POSTGRES_PASSWORD: 40027020
      POSTGRES_DB: bookmarkapp
    networks:
      - infinitedim
networks:
  infinitedim:
